-- The canonical extraction-owned database schema now lives at:
--   packages/extraction/prisma/schema.prisma
--
-- Its checked-in PostgreSQL migration lives at:
--   packages/extraction/prisma/migrations/20260718120000_init_extraction_memory/migration.sql
--
-- Keeping the schema beside the only stage allowed to write it prevents the ingestion
-- handoff contract from becoming coupled to extraction's persistence implementation.
